### ISSUE TITLE
Lab 14 not present in ES repo

### ISSUE THREAD

**Issue by MOC-Labs-Review** [MicrosoftLearning/AZ500-AzureSecurityTechnologies.es-es#1]
https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies.es-es/tree/main/Instructions/Labs

Lab 14 not present in ES version

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
Now, the lab14 page show it.
https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies.es-es/blob/main/Instructions/Labs/LAB_14_Microsoft%20Defender%20for%20Cloud.md
should be closed.

**Comment by chriscarty00** [comment]
Verified https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies.es-es/blob/main/Instructions/Labs/LAB_14_Microsoft%20Defender%20for%20Cloud.md is present
